"""
Linux Network Management
Author: BrillConsulting
Description: Complete network configuration, routing, DNS, and firewall management
"""

import json
from typing import Dict, List, Any, Optional
from datetime import datetime


class NetworkManager:
    """Comprehensive Linux network management"""

    def __init__(self, hostname: str = 'localhost'):
        """
        Initialize network manager

        Args:
            hostname: Server hostname
        """
        self.hostname = hostname
        self.interfaces = []
        self.routes = []
        self.dns_records = []
        self.firewall_rules = []
        self.vpn_connections = []

    def configure_interface(self, interface_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Configure network interface

        Args:
            interface_config: Interface configuration

        Returns:
            Interface details
        """
        interface = {
            'name': interface_config.get('name', 'eth0'),
            'ip_address': interface_config.get('ip_address', '192.168.1.100'),
            'netmask': interface_config.get('netmask', '255.255.255.0'),
            'gateway': interface_config.get('gateway', '192.168.1.1'),
            'dns_servers': interface_config.get('dns_servers', ['8.8.8.8', '8.8.4.4']),
            'mtu': interface_config.get('mtu', 1500),
            'state': 'up',
            'method': interface_config.get('method', 'static'),
            'configured_at': datetime.now().isoformat()
        }

        self.interfaces.append(interface)

        # Generate netplan configuration
        netplan_config = f"""network:
  version: 2
  renderer: networkd
  ethernets:
    {interface['name']}:
      addresses:
        - {interface['ip_address']}/{self._cidr_from_netmask(interface['netmask'])}
      gateway4: {interface['gateway']}
      nameservers:
        addresses: [{', '.join(interface['dns_servers'])}]
      mtu: {interface['mtu']}
"""

        print(f"✓ Interface configured: {interface['name']}")
        print(f"  IP: {interface['ip_address']}, Gateway: {interface['gateway']}")
        print(f"  DNS: {', '.join(interface['dns_servers'])}")
        print(f"\n  Netplan configuration:")
        print(f"  {netplan_config}")
        return interface

    def add_route(self, route_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Add static route

        Args:
            route_config: Route configuration

        Returns:
            Route details
        """
        route = {
            'destination': route_config.get('destination', '10.0.0.0/8'),
            'gateway': route_config.get('gateway', '192.168.1.1'),
            'interface': route_config.get('interface', 'eth0'),
            'metric': route_config.get('metric', 100),
            'created_at': datetime.now().isoformat()
        }

        self.routes.append(route)

        command = f"ip route add {route['destination']} via {route['gateway']} dev {route['interface']} metric {route['metric']}"

        print(f"✓ Route added: {route['destination']} via {route['gateway']}")
        print(f"  Interface: {route['interface']}, Metric: {route['metric']}")
        print(f"  Command: {command}")
        return route

    def configure_dns(self, dns_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Configure DNS settings

        Args:
            dns_config: DNS configuration

        Returns:
            DNS configuration details
        """
        dns = {
            'nameservers': dns_config.get('nameservers', ['8.8.8.8', '8.8.4.4', '1.1.1.1']),
            'search_domains': dns_config.get('search_domains', ['example.com', 'local']),
            'options': dns_config.get('options', ['timeout:2', 'attempts:3']),
            'configured_at': datetime.now().isoformat()
        }

        resolv_conf = f"""# Generated by NetworkManager
# {datetime.now().isoformat()}

"""
        for ns in dns['nameservers']:
            resolv_conf += f"nameserver {ns}\n"

        if dns['search_domains']:
            resolv_conf += f"search {' '.join(dns['search_domains'])}\n"

        if dns['options']:
            resolv_conf += f"options {' '.join(dns['options'])}\n"

        print(f"✓ DNS configured")
        print(f"  Nameservers: {', '.join(dns['nameservers'])}")
        print(f"  Search domains: {', '.join(dns['search_domains'])}")
        print(f"\n  /etc/resolv.conf:")
        print(f"  {resolv_conf}")
        return dns

    def setup_bridge(self, bridge_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Setup network bridge

        Args:
            bridge_config: Bridge configuration

        Returns:
            Bridge details
        """
        bridge = {
            'name': bridge_config.get('name', 'br0'),
            'interfaces': bridge_config.get('interfaces', ['eth0', 'eth1']),
            'ip_address': bridge_config.get('ip_address', '192.168.10.1'),
            'netmask': bridge_config.get('netmask', '255.255.255.0'),
            'stp': bridge_config.get('stp', True),
            'forward_delay': bridge_config.get('forward_delay', 15),
            'created_at': datetime.now().isoformat()
        }

        commands = [
            f"ip link add name {bridge['name']} type bridge",
            f"ip link set {bridge['name']} up"
        ]

        for iface in bridge['interfaces']:
            commands.append(f"ip link set {iface} master {bridge['name']}")

        commands.append(f"ip addr add {bridge['ip_address']}/{self._cidr_from_netmask(bridge['netmask'])} dev {bridge['name']}")

        print(f"✓ Bridge configured: {bridge['name']}")
        print(f"  Interfaces: {', '.join(bridge['interfaces'])}")
        print(f"  IP: {bridge['ip_address']}, STP: {bridge['stp']}")
        print(f"\n  Commands:")
        for cmd in commands:
            print(f"    {cmd}")
        return bridge

    def setup_vlan(self, vlan_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Setup VLAN interface

        Args:
            vlan_config: VLAN configuration

        Returns:
            VLAN details
        """
        vlan = {
            'parent_interface': vlan_config.get('parent_interface', 'eth0'),
            'vlan_id': vlan_config.get('vlan_id', 100),
            'vlan_name': f"{vlan_config.get('parent_interface', 'eth0')}.{vlan_config.get('vlan_id', 100)}",
            'ip_address': vlan_config.get('ip_address', '192.168.100.1'),
            'netmask': vlan_config.get('netmask', '255.255.255.0'),
            'created_at': datetime.now().isoformat()
        }

        commands = [
            f"ip link add link {vlan['parent_interface']} name {vlan['vlan_name']} type vlan id {vlan['vlan_id']}",
            f"ip addr add {vlan['ip_address']}/{self._cidr_from_netmask(vlan['netmask'])} dev {vlan['vlan_name']}",
            f"ip link set {vlan['vlan_name']} up"
        ]

        print(f"✓ VLAN configured: {vlan['vlan_name']}")
        print(f"  VLAN ID: {vlan['vlan_id']}, Parent: {vlan['parent_interface']}")
        print(f"  IP: {vlan['ip_address']}")
        print(f"\n  Commands:")
        for cmd in commands:
            print(f"    {cmd}")
        return vlan

    def setup_bonding(self, bond_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Setup network bonding (link aggregation)

        Args:
            bond_config: Bonding configuration

        Returns:
            Bond details
        """
        bond = {
            'name': bond_config.get('name', 'bond0'),
            'mode': bond_config.get('mode', 'active-backup'),
            'interfaces': bond_config.get('interfaces', ['eth0', 'eth1']),
            'miimon': bond_config.get('miimon', 100),
            'primary': bond_config.get('primary', 'eth0'),
            'ip_address': bond_config.get('ip_address', '192.168.1.100'),
            'netmask': bond_config.get('netmask', '255.255.255.0'),
            'created_at': datetime.now().isoformat()
        }

        netplan_config = f"""network:
  version: 2
  renderer: networkd
  bonds:
    {bond['name']}:
      addresses:
        - {bond['ip_address']}/{self._cidr_from_netmask(bond['netmask'])}
      interfaces: [{', '.join(bond['interfaces'])}]
      parameters:
        mode: {bond['mode']}
        mii-monitor-interval: {bond['miimon']}
        primary: {bond['primary']}
"""

        print(f"✓ Bonding configured: {bond['name']}")
        print(f"  Mode: {bond['mode']}, Interfaces: {', '.join(bond['interfaces'])}")
        print(f"  IP: {bond['ip_address']}")
        print(f"\n  Netplan configuration:")
        print(f"  {netplan_config}")
        return bond

    def configure_nat(self, nat_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Configure NAT (Network Address Translation)

        Args:
            nat_config: NAT configuration

        Returns:
            NAT details
        """
        nat = {
            'internal_interface': nat_config.get('internal_interface', 'eth0'),
            'external_interface': nat_config.get('external_interface', 'eth1'),
            'internal_network': nat_config.get('internal_network', '192.168.1.0/24'),
            'masquerade': nat_config.get('masquerade', True),
            'configured_at': datetime.now().isoformat()
        }

        commands = [
            "# Enable IP forwarding",
            "echo 1 > /proc/sys/net/ipv4/ip_forward",
            "sysctl -w net.ipv4.ip_forward=1",
            "",
            "# Configure NAT rules",
            f"iptables -t nat -A POSTROUTING -o {nat['external_interface']} -j MASQUERADE",
            f"iptables -A FORWARD -i {nat['internal_interface']} -o {nat['external_interface']} -j ACCEPT",
            f"iptables -A FORWARD -i {nat['external_interface']} -o {nat['internal_interface']} -m state --state RELATED,ESTABLISHED -j ACCEPT"
        ]

        print(f"✓ NAT configured")
        print(f"  Internal: {nat['internal_interface']} ({nat['internal_network']})")
        print(f"  External: {nat['external_interface']}")
        print(f"\n  Commands:")
        for cmd in commands:
            print(f"    {cmd}")
        return nat

    def setup_vpn_wireguard(self, vpn_config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Setup WireGuard VPN

        Args:
            vpn_config: VPN configuration

        Returns:
            VPN details
        """
        vpn = {
            'interface': vpn_config.get('interface', 'wg0'),
            'private_key': vpn_config.get('private_key', '[PRIVATE_KEY]'),
            'address': vpn_config.get('address', '10.0.0.1/24'),
            'listen_port': vpn_config.get('listen_port', 51820),
            'peers': vpn_config.get('peers', []),
            'created_at': datetime.now().isoformat()
        }

        wg_config = f"""[Interface]
PrivateKey = {vpn['private_key']}
Address = {vpn['address']}
ListenPort = {vpn['listen_port']}

"""
        for peer in vpn['peers']:
            wg_config += f"""[Peer]
PublicKey = {peer.get('public_key', '[PUBLIC_KEY]')}
AllowedIPs = {peer.get('allowed_ips', '10.0.0.2/32')}
Endpoint = {peer.get('endpoint', '1.2.3.4:51820')}
PersistentKeepalive = 25

"""

        print(f"✓ WireGuard VPN configured: {vpn['interface']}")
        print(f"  Address: {vpn['address']}, Port: {vpn['listen_port']}")
        print(f"  Peers: {len(vpn['peers'])}")
        print(f"\n  /etc/wireguard/{vpn['interface']}.conf:")
        print(f"  {wg_config}")
        return vpn

    def test_connectivity(self, target: str) -> Dict[str, Any]:
        """
        Test network connectivity

        Args:
            target: Target host/IP

        Returns:
            Test results
        """
        result = {
            'target': target,
            'ping_success': True,
            'latency_ms': 15.3,
            'packet_loss': 0.0,
            'traceroute_hops': 8,
            'tested_at': datetime.now().isoformat()
        }

        commands = [
            f"ping -c 4 {target}",
            f"traceroute {target}",
            f"mtr -r -c 10 {target}",
            f"nc -zv {target} 443"
        ]

        print(f"✓ Connectivity test: {target}")
        print(f"  Ping: {'Success' if result['ping_success'] else 'Failed'}")
        print(f"  Latency: {result['latency_ms']}ms, Loss: {result['packet_loss']}%")
        print(f"\n  Test commands:")
        for cmd in commands:
            print(f"    {cmd}")
        return result

    def _cidr_from_netmask(self, netmask: str) -> int:
        """Convert netmask to CIDR notation"""
        return sum([bin(int(x)).count('1') for x in netmask.split('.')])

    def get_network_info(self) -> Dict[str, Any]:
        """Get network manager information"""
        return {
            'hostname': self.hostname,
            'interfaces': len(self.interfaces),
            'routes': len(self.routes),
            'firewall_rules': len(self.firewall_rules),
            'vpn_connections': len(self.vpn_connections),
            'timestamp': datetime.now().isoformat()
        }


def demo():
    """Demonstrate network management"""

    print("=" * 60)
    print("Linux Network Management Demo")
    print("=" * 60)

    manager = NetworkManager(hostname='prod-server-01')

    print("\n1. Configuring network interface...")
    interface = manager.configure_interface({
        'name': 'eth0',
        'ip_address': '192.168.1.100',
        'netmask': '255.255.255.0',
        'gateway': '192.168.1.1',
        'dns_servers': ['8.8.8.8', '1.1.1.1'],
        'mtu': 1500
    })

    print("\n2. Adding static route...")
    route = manager.add_route({
        'destination': '10.0.0.0/8',
        'gateway': '192.168.1.254',
        'interface': 'eth0',
        'metric': 100
    })

    print("\n3. Configuring DNS...")
    dns = manager.configure_dns({
        'nameservers': ['8.8.8.8', '8.8.4.4', '1.1.1.1'],
        'search_domains': ['example.com', 'internal.local'],
        'options': ['timeout:2', 'attempts:3']
    })

    print("\n4. Setting up network bridge...")
    bridge = manager.setup_bridge({
        'name': 'br0',
        'interfaces': ['eth0', 'eth1'],
        'ip_address': '192.168.10.1',
        'netmask': '255.255.255.0',
        'stp': True
    })

    print("\n5. Setting up VLAN...")
    vlan = manager.setup_vlan({
        'parent_interface': 'eth0',
        'vlan_id': 100,
        'ip_address': '192.168.100.1',
        'netmask': '255.255.255.0'
    })

    print("\n6. Setting up bonding...")
    bond = manager.setup_bonding({
        'name': 'bond0',
        'mode': 'active-backup',
        'interfaces': ['eth2', 'eth3'],
        'ip_address': '192.168.2.100',
        'netmask': '255.255.255.0'
    })

    print("\n7. Configuring NAT...")
    nat = manager.configure_nat({
        'internal_interface': 'eth0',
        'external_interface': 'eth1',
        'internal_network': '192.168.1.0/24'
    })

    print("\n8. Setting up WireGuard VPN...")
    vpn = manager.setup_vpn_wireguard({
        'interface': 'wg0',
        'address': '10.0.0.1/24',
        'listen_port': 51820,
        'peers': [
            {
                'public_key': 'peer1_public_key',
                'allowed_ips': '10.0.0.2/32',
                'endpoint': '203.0.113.5:51820'
            }
        ]
    })

    print("\n9. Testing connectivity...")
    test = manager.test_connectivity('8.8.8.8')

    print("\n10. Network summary:")
    info = manager.get_network_info()
    print(f"  Hostname: {info['hostname']}")
    print(f"  Interfaces: {info['interfaces']}")
    print(f"  Routes: {info['routes']}")
    print(f"  VPN connections: {info['vpn_connections']}")

    print("\n" + "=" * 60)
    print("Demo completed successfully!")
    print("=" * 60)


if __name__ == "__main__":
    demo()
